apiVersion : apps/v1
kind: Deployment
metadata:
  name: beathubmultiarenasdeliveryauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beathubmultiarenasdeliveryauth
  template:
    metadata:
      labels:
        app: beathubmultiarenasdeliveryauth
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: beathubmultiarenasdeliveryauth
          image: beathubconnectposcontainer.azurecr.io/beathubmultiarenasdeliveryauth
          ports:
          - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/api/v1/auth"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://57.169.188.42:5432/multiarenas_beathub?currentSchema=auth,public"
            - name: SPRING_DATASOURCE_USERNAME
              value: "multi_user_stg"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "JS.23AnDFAsd$3"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "validate"
            - name: SPRING_JPA_SHOW_SQL
              value: "false"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"          
            limits:
              cpu: "500m"
              memory: "256Mi"